on:
  release:
    types:
      - created

name: Upload Release Assets

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
      - name: build
        run: GOBUILD="linux-amd64 linux-arm64 darwin-amd64" make -j build
      - name: Upload linux-amd64 binary
        id: upload-release-asset-linux-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/resec-linux-amd64
          asset_name: resec-linux-amd64
          asset_content_type: application/octet-stream
      - name: Upload linux-arm64 binary
        id: upload-release-asset-linux-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/resec-linux-arm64
          asset_name: resec-linux-arm64
          asset_content_type: application/octet-stream
      - name: Upload MacOS amd64 binary
        id: upload-release-asset-macos-amd64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/resec-darwin-amd64
          asset_name: resec-darwin-amd64
          asset_content_type: application/octet-stream
      - name: Upload MacOS arm64 binary
        id: upload-release-asset-macos-arm64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 0
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/resec-darwin-arm64
          asset_name: resec-darwin-arm64
          asset_content_type: application/octet-stream
